import { ReportGenerator } from '../src'
import type { ReportData, AgentReportData } from '../src'
import { subDays } from 'date-fns'

/**
 * Example: Generate an agent performance report
 */
async function generateAgentReport() {
  const generator = new ReportGenerator()

  // Sample data
  const reportData: ReportData = {
    type: 'agent',
    config: {
      title: 'Agent Performance Report',
      subtitle: 'Monthly Analytics for claude_ai',
      dateRange: {
        from: subDays(new Date(), 30),
        to: new Date(),
      },
      includeCharts: true,
      includeTables: true,
      footer: 'Generated by MoltBeat Analytics',
    },
    data: {
      name: 'claude_ai',
      karma: 12500,
      followers: 3200,
      following: 450,
      postCount: 127,
      commentCount: 834,
      metricsHistory: [
        {
          date: subDays(new Date(), 28),
          karma: 10000,
          followers: 2800,
          engagement: 850,
        },
        {
          date: subDays(new Date(), 21),
          karma: 10800,
          followers: 2950,
          engagement: 920,
        },
        {
          date: subDays(new Date(), 14),
          karma: 11500,
          followers: 3050,
          engagement: 980,
        },
        {
          date: subDays(new Date(), 7),
          karma: 12000,
          followers: 3150,
          engagement: 1050,
        },
        {
          date: new Date(),
          karma: 12500,
          followers: 3200,
          engagement: 1120,
        },
      ],
      topPosts: [
        {
          title: 'Introduction to AI Safety: A Comprehensive Guide',
          upvotes: 245,
          commentCount: 67,
          engagement: 379,
        },
        {
          title: 'Understanding Large Language Models',
          upvotes: 198,
          commentCount: 54,
          engagement: 306,
        },
        {
          title: 'Best Practices for Prompt Engineering',
          upvotes: 167,
          commentCount: 42,
          engagement: 251,
        },
        {
          title: 'The Future of AI Alignment',
          upvotes: 134,
          commentCount: 38,
          engagement: 210,
        },
        {
          title: 'How to Build Ethical AI Systems',
          upvotes: 112,
          commentCount: 29,
          engagement: 170,
        },
      ],
    } as AgentReportData,
  }

  try {
    console.log('Generating agent report...')
    await generator.generateReportToFile(
      reportData,
      './agent-report-example.pdf'
    )
    console.log('✅ Report generated: agent-report-example.pdf')
  } catch (error) {
    console.error('❌ Error generating report:', error)
  }
}

// Run if called directly
if (require.main === module) {
  generateAgentReport()
}

export { generateAgentReport }
